In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel("/content/upi_transactions_raw.xlsx",sheet_name="upi_data")
df.head()

,Month,Financial_Year,Banks_Live,UPI_Volume_Mn,UPI_Value_Cr,Month_Start_Date,Year,Month_Number,Quarter,Avg_Transaction_Value
0,April-2021,2021-22,220,2641.06,493663.68,2021-04-01,2021,4,Q1,186.918767
1,May-2021,2021-22,224,2539.57,490638.65,2021-05-01,2021,5,Q1,193.197530
2,June-2021,2021-22,229,2807.51,547373.17,2021-06-01,2021,6,Q1,194.967487
3,July-2021,2021-22,235,3247.82,606281.14,2021-07-01,2021,7,Q2,186.673258
4,August-2021,2021-22,249,3555.55,639116.95,2021-08-01,2021,8,Q2,179.751923

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Month                  63 non-null     object
 1   Financial_Year         63 non-null     object
 2   Banks_Live             63 non-null     int64
 3   UPI_Volume_Mn          63 non-null     float64
 4   UPI_Value_Cr           63 non-null     float64
 5   Month_Start_Date       63 non-null     datetime64[ns]
 6   Year                   63 non-null     int64
 7   Month_Number           63 non-null     int64
 8   Quarter                63 non-null     object
 9   Avg_Transaction_Value  63 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 5.1+ KB

In [7]:
print("Dataset shape:")
print(df.shape)

print("\n-----------------------------")
print("Column names:")
print(df.columns.tolist())

Dataset shape:
(63, 10)

-----------------------------
Column names:
['Month', 'Financial_Year', 'Banks_Live', 'UPI_Volume_Mn', 'UPI_Value_Cr', 'Month_Start_Date', 'Year', 'Month_Number', 'Quarter', 'Avg_Transaction_Value']

In [8]:
print("Data types:")
df.dtypes

Data types:

Month                            object
Financial_Year                   object
Banks_Live                        int64
UPI_Volume_Mn                   float64
UPI_Value_Cr                    float64
Month_Start_Date         datetime64[ns]
Year                              int64
Month_Number                      int64
Quarter                          object
Avg_Transaction_Value           float64
dtype: object

In [9]:
print("\nMissing values in each column:\n")
print(df.isnull().sum())

Missing values in each column:

Month                    0
Financial_Year           0
Banks_Live               0
UPI_Volume_Mn            0
UPI_Value_Cr             0
Month_Start_Date         0
Year                     0
Month_Number             0
Quarter                  0
Avg_Transaction_Value    0
dtype: int64

In [10]:
# Step 5: Sort dataset by Month_Start_Date
df = df.sort_values("Month_Start_Date").reset_index(drop=True)

print(df.head())

         Month Financial_Year  Banks_Live  UPI_Volume_Mn  UPI_Value_Cr  \
0   April-2021        2021-22         220        2641.06     493663.68
1     May-2021        2021-22         224        2539.57     490638.65
2    June-2021        2021-22         229        2807.51     547373.17
3    July-2021        2021-22         235        3247.82     606281.14
4  August-2021        2021-22         249        3555.55     639116.95

  Month_Start_Date  Year  Month_Number Quarter  Avg_Transaction_Value
0       2021-04-01  2021             4      Q1             186.918767
1       2021-05-01  2021             5      Q1             193.197530
2       2021-06-01  2021             6      Q1             194.967487
3       2021-07-01  2021             7      Q2             186.673258
4       2021-08-01  2021             8      Q2             179.751923

In [11]:
print("Last 5 rows after sorting:\n")
print(df.tail())

Last 5 rows after sorting:

            Month Financial_Year  Banks_Live  UPI_Volume_Mn  UPI_Value_Cr  \
58  February-2026        2025-26         694       20394.18    2684229.29
59     March-2026        2025-26         705       22641.11    2952542.05
60     April-2026        2026-27         713       22346.80    2902988.05
61       May-2026        2026-27         720       23201.93    2990424.21
62      June-2026        2026-27         731       22716.07    2892138.67

   Month_Start_Date  Year  Month_Number Quarter  Avg_Transaction_Value
58       2026-02-01  2026             2      Q4             131.617417
59       2026-03-01  2026             3      Q4             130.406241
60       2026-04-01  2026             4      Q1             129.906208
61       2026-05-01  2026             5      Q1             128.886873
62       2026-06-01  2026             6      Q1             127.316859

Month-on-Month growth

In [12]:
df["MoM_Volume_Growth_%"] = (df["UPI_Volume_Mn"].pct_change() * 100).round(2)
df["MoM_Value_Growth_%"] = (df["UPI_Value_Cr"].pct_change() * 100).round(2)

In [13]:
print(df[[
    "Month",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "MoM_Volume_Growth_%",
    "MoM_Value_Growth_%"
]].head(10))

            Month  UPI_Volume_Mn  UPI_Value_Cr  MoM_Volume_Growth_%  \
0      April-2021        2641.06     493663.68                  NaN
1        May-2021        2539.57     490638.65                -3.84
2       June-2021        2807.51     547373.17                10.55
3       July-2021        3247.82     606281.14                15.68
4     August-2021        3555.55     639116.95                 9.47
5  September-2021        3654.30     654351.81                 2.78
6    October-2021        4218.65     771444.98                15.44
7   November-2021        4186.48     768436.11                -0.76
8   December-2021        4566.30     826848.22                 9.07
9    January-2022        4617.15     831993.11                 1.11

   MoM_Value_Growth_%
0                 NaN
1               -0.61
2               11.56
3               10.76
4                5.42
5                2.38
6               17.89
7               -0.39
8                7.60
9                0.62

Year-on-Year growth

In [14]:
df["YoY_Volume_Growth_%"] = (df["UPI_Volume_Mn"].pct_change(periods=12) * 100).round(2)
df["YoY_Value_Growth_%"] = (df["UPI_Value_Cr"].pct_change(periods=12) * 100).round(2)

In [63]:
print(df[[
    "Month",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "MoM_Volume_Growth_%",
    "MoM_Value_Growth_%",
    "YoY_Volume_Growth_%",
    "YoY_Value_Growth_%"
]].head(15))

             Month  UPI_Volume_Mn  UPI_Value_Cr  MoM_Volume_Growth_%  \
0       April-2021        2641.06     493663.68                  NaN
1         May-2021        2539.57     490638.65                -3.84
2        June-2021        2807.51     547373.17                10.55
3        July-2021        3247.82     606281.14                15.68
4      August-2021        3555.55     639116.95                 9.47
5   September-2021        3654.30     654351.81                 2.78
6     October-2021        4218.65     771444.98                15.44
7    November-2021        4186.48     768436.11                -0.76
8    December-2021        4566.30     826848.22                 9.07
9     January-2022        4617.15     831993.11                 1.11
10   February-2022        4527.49     826843.00                -1.94
11      March-2022        5405.65     960581.66                19.40
12      April-2022        5583.05     983302.27                 3.28
13        May-2022        5955.20    1041520.07                 6.67
14       June-2022        5862.75    1014384.31                -1.55

    MoM_Value_Growth_%  YoY_Volume_Growth_%  YoY_Value_Growth_%
0                  NaN                  NaN                 NaN
1                -0.61                  NaN                 NaN
2                11.56                  NaN                 NaN
3                10.76                  NaN                 NaN
4                 5.42                  NaN                 NaN
5                 2.38                  NaN                 NaN
6                17.89                  NaN                 NaN
7                -0.39                  NaN                 NaN
8                 7.60                  NaN                 NaN
9                 0.62                  NaN                 NaN
10               -0.62                  NaN                 NaN
11               16.17                  NaN                 NaN
12                2.37               111.39               99.18
13                5.92               134.50              112.28
14               -2.61               108.82               85.32

In [15]:
df["Month_Name"] = df["Month_Start_Date"].dt.strftime("%B")
df["Calendar_Quarter"] = df["Month_Start_Date"].dt.quarter

In [16]:
print(df.head())

         Month Financial_Year  Banks_Live  UPI_Volume_Mn  UPI_Value_Cr  \
0   April-2021        2021-22         220        2641.06     493663.68
1     May-2021        2021-22         224        2539.57     490638.65
2    June-2021        2021-22         229        2807.51     547373.17
3    July-2021        2021-22         235        3247.82     606281.14
4  August-2021        2021-22         249        3555.55     639116.95

  Month_Start_Date  Year  Month_Number Quarter  Avg_Transaction_Value  \
0       2021-04-01  2021             4      Q1             186.918767
1       2021-05-01  2021             5      Q1             193.197530
2       2021-06-01  2021             6      Q1             194.967487
3       2021-07-01  2021             7      Q2             186.673258
4       2021-08-01  2021             8      Q2             179.751923

   MoM_Volume_Growth_%  MoM_Value_Growth_%  YoY_Volume_Growth_%  \
0                  NaN                 NaN                  NaN
1                -3.84               -0.61                  NaN
2                10.55               11.56                  NaN
3                15.68               10.76                  NaN
4                 9.47                5.42                  NaN

   YoY_Value_Growth_% Month_Name  Calendar_Quarter
0                 NaN      April                 2
1                 NaN        May                 2
2                 NaN       June                 2
3                 NaN       July                 3
4                 NaN     August                 3

In [18]:
df.columns.tolist()

['Month',
 'Financial_Year',
 'Banks_Live',
 'UPI_Volume_Mn',
 'UPI_Value_Cr',
 'Month_Start_Date',
 'Year',
 'Month_Number',
 'Quarter',
 'Avg_Transaction_Value',
 'MoM_Volume_Growth_%',
 'MoM_Value_Growth_%',
 'YoY_Volume_Growth_%',
 'YoY_Value_Growth_%',
 'Month_Name',
 'Calendar_Quarter']

In [21]:
df.to_csv("upi_transactions.csv", index=False)

print("File exported successfully ")

File exported successfully

yearly summary table

In [36]:
yearly_summary = df.groupby("Financial_Year").agg({
    "UPI_Volume_Mn": "sum",
    "UPI_Value_Cr": "sum",
    "Banks_Live": "mean",
    "Avg_Transaction_Value": "mean",
    "MoM_Volume_Growth_%": "mean",
    "MoM_Value_Growth_%": "mean"
}).reset_index().round(2)

In [37]:
yearly_summary.columns = [
    "Financial_Year",
    "Total_UPI_Volume_Mn",
    "Total_UPI_Value_Cr",
    "Avg_Banks_Live",
    "Avg_Transaction_Value",
    "Avg_MoM_Volume_Growth_%",
    "Avg_MoM_Value_Growth_%"
]
yearly_summary

,Financial_Year,Total_UPI_Volume_Mn,Total_UPI_Value_Cr,Avg_Banks_Live,Avg_Transaction_Value,Avg_MoM_Volume_Growth_%,Avg_MoM_Value_Growth_%
0,2021-22,45967.53,8417572.48,262.33,184.05,7.00,6.43
1,2022-23,83751.14,13920676.35,359.00,166.77,4.16,3.38
2,2023-24,131129.83,19995085.51,499.25,152.86,3.78,2.91
3,2024-25,185866.02,26056954.65,624.08,140.46,2.77,2.10
4,2025-26,241616.88,31423249.71,684.67,130.10,1.89,1.60
5,2026-27,68264.80,8785550.93,721.33,128.70,0.15,-0.65

quarterly summary table

In [38]:
quarterly_summary = df.groupby(["Financial_Year", "Quarter"]).agg({
    "UPI_Volume_Mn": "sum",
    "UPI_Value_Cr": "sum",
    "Banks_Live": "mean",
    "Avg_Transaction_Value": "mean",
    "MoM_Volume_Growth_%": "mean",
    "MoM_Value_Growth_%": "mean"
}).reset_index().round(2)

In [42]:
quarterly_summary.columns = [
    "Financial_Year",
    "Quarter",
    "Total_UPI_Volume_Mn",
    "Total_UPI_Value_Cr",
    "Avg_Banks_Live",
    "Avg_Transaction_Value",
    "Avg_MoM_Volume_Growth_%",
    "Avg_MoM_Value_Growth_%"
]
quarterly_summary.head()

,Financial_Year,Quarter,Total_UPI_Volume_Mn,Total_UPI_Value_Cr,Avg_Banks_Live,Avg_Transaction_Value,Avg_MoM_Volume_Growth_%,Avg_MoM_Value_Growth_%
0,2021-22,Q1,7988.14,1531675.50,224.33,191.69,3.36,5.48
1,2021-22,Q2,10457.67,1899749.90,247.67,181.83,9.31,6.19
2,2021-22,Q3,12971.43,2366729.31,272.33,182.50,7.92,8.37
3,2021-22,Q4,14550.29,2619417.77,305.00,180.17,6.19,5.39
4,2022-23,Q1,17401.00,3039206.65,323.00,174.68,2.80,1.89

Top 5 months by UPI Volume and Value

In [49]:
top_volume_months = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "Banks_Live"
]].sort_values("UPI_Volume_Mn", ascending=False).head(5)
top_volume_months

           Month Financial_Year  UPI_Volume_Mn  UPI_Value_Cr  Banks_Live
61      May-2026        2026-27       23201.93    2990424.21         720
62     June-2026        2026-27       22716.07    2892138.67         731
59    March-2026        2025-26       22641.11    2952542.05         705
60    April-2026        2026-27       22346.80    2902988.05         713
57  January-2026        2025-26       21703.44    2833481.22         691

In [52]:
top_value_months = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "Banks_Live"
]].sort_values("UPI_Value_Cr", ascending=False).head(5)
top_value_months

           Month Financial_Year  UPI_Volume_Mn  UPI_Value_Cr  Banks_Live
61      May-2026        2026-27       23201.93    2990424.21         720
59    March-2026        2025-26       22641.11    2952542.05         705
60    April-2026        2026-27       22346.80    2902988.05         713
62     June-2026        2026-27       22716.07    2892138.67         731
57  January-2026        2025-26       21703.44    2833481.22         691

Top 5 months by MoM Volume Growth %

In [53]:
top_mom_volume_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "MoM_Volume_Growth_%"
]].sort_values("MoM_Volume_Growth_%", ascending=False).head(5)
top_mom_volume_growth

           Month Financial_Year  UPI_Volume_Mn  MoM_Volume_Growth_%
11    March-2022        2021-22        5405.65                19.40
3      July-2021        2021-22        3247.82                15.68
6   October-2021        2021-22        4218.65                15.44
23    March-2023        2022-23        8685.30                15.27
47    March-2025        2024-25       18301.51                13.63

Top 5 months by MoM Value Growth %

In [54]:
top_mom_value_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Value_Cr",
    "MoM_Value_Growth_%"
]].sort_values("MoM_Value_Growth_%", ascending=False).head(5)
top_mom_value_growth

           Month Financial_Year  UPI_Value_Cr  MoM_Value_Growth_%
6   October-2021        2021-22     771444.98               17.89
11    March-2022        2021-22     960581.66               16.17
23    March-2023        2022-23    1410443.01               14.13
42  October-2024        2024-25    2349821.46               13.85
47    March-2025        2024-25    2477221.61               12.78

Top 5 months by YoY Volume Growth %

In [57]:
top_yoy_volume_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "YoY_Volume_Growth_%"
]].sort_values("YoY_Volume_Growth_%", ascending=False).head(5)
top_yoy_volume_growth

             Month Financial_Year  UPI_Volume_Mn  YoY_Volume_Growth_%
13        May-2022        2022-23        5955.20               134.50
12      April-2022        2022-23        5583.05               111.39
14       June-2022        2022-23        5862.75               108.82
15       July-2022        2022-23        6288.40                93.62
17  September-2022        2022-23        6780.80                85.56

Top 5 months by YoY Value Growth %

In [58]:
top_yoy_value_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Value_Cr",
    "YoY_Value_Growth_%"
]].sort_values("YoY_Value_Growth_%", ascending=False).head(5)
top_yoy_value_growth

             Month Financial_Year  UPI_Value_Cr  YoY_Value_Growth_%
13        May-2022        2022-23    1041520.07              112.28
12      April-2022        2022-23     983302.27               99.18
14       June-2022        2022-23    1014384.31               85.32
15       July-2022        2022-23    1062991.76               75.33
17  September-2022        2022-23    1116438.10               70.62

In [60]:
df.to_csv("upi_transactions.csv", index=False)

print("File exported successfully ")

File exported successfully